server:
  port: 8080
spring:
  application:
    name: servico-file-config
service-parametro:
  parametro1: "Olá"
  parametro2: "Mundo"
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  
 
