
server:
  port: 8080
spring:
  application:
    name: servico-file-config
service-parametro:
  parametro1: "dev"
  parametro2: "dev"
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
